version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: curriculum
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.5.1
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file: .env
volumes:
  db_data:
