# Create a semantic release, including
# - a package.json version number
# - an updated change log file
# - a Github release, which will trigger a deployment
name: Create Github Release

# All changes to `main` have gone through
# automated checks and should have gone
# through code review and manual checks
# where appropriate.
on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    name: semantic release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      # Install.
      - run: npm ci

      # Create Github release using semantic-release package.
      # See config here release.config.js
      # Note, this runs on `main` and _creates_ the release tag.
      # Also updates the version number in the package.json file,
      # and updates the changelog file.
      - name: do release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: npx semantic-release
