name: Deployment Checks

on: deployment_status

jobs:
  dump_github_event:
    uses: ./.github/workflows/dump_event.yml

  # A placeholder workflow triggered by deployment events.
  pa11y:
    # Only want to run on success, otherwise it might be "pending", or "failure".
    if: ${{ github.event.deployment_status.state == 'success' }}
    name: Pa11y
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Note we can't use caching here, because caching needs GITHUB_REF to be defined,
      # and Vercel deployment_status events set deployment.ref to the SHA, not the triggering
      # branch or pull request.
      # https://github.com/actions/cache/issues/319
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci

      - name: Log out URL
        run: echo "${{ github.event.deployment_status.target_url }}"

      # Run pa11y
      - name: Pa11y CI
        id: run_pa11y
        run: npm run pa11y
        env:
          BASE_URL: ${{ github.event.deployment_status.target_url }}

      # Set a custom status because there may be more than one deployment_status
      # event due to alternatively themed deployments, and multiple runs of this
      # workflow will overwrite each other in the PR checks UI, but custom statuses
      # will remain
      - uses: ./.github/actions/custom_statuses
        name: Set Pa11y check result
        if: ${{ always() }}
        with:
          description: Pa11y (${{github.event.deployment_status.environment}})
          state: ${{ steps.run_pa11y.outcome }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # A placeholder workflow triggered by deployment events.
  percy:
    # Only want to run on success, otherwise it might be "pending", or "failure".
    # Filter out alt theme deployments
    if: ${{ github.event.deployment_status.state == 'success' && !contains(github.event.deployment_status.environment, 'alt-theme')}}
    name: Percy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Note we can't use caching here, because caching needs GITHUB_REF to be defined,
      # and Vercel deployment_status events set deployment.ref to the SHA, not the triggering
      # branch or pull request.
      # https://github.com/actions/cache/issues/319
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm ci

      - name: Log out URL
        run: echo "${{ github.event.deployment_status.target_url }}"

      - uses: ./.github/actions/ref_from_sha
        name: Get PR Ref from SHA
        id: ref_from_sha
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: print ref from sha
        run: echo "${{ steps.ref_from_sha.outputs.head_ref }}"

      - name: run percy
        id: run_percy
        run: "echo 'do some Percy things'"

      # Set custom status so results preserved between multiple
      # deployment events from same commit
      - uses: ./.github/actions/custom_statuses
        name: Set Percy check result
        if: ${{ always() }}
        with:
          description: Percy (${{github.event.deployment_status.environment}})
          state: ${{ steps.run_percy.outcome }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
