# Deploy a release tag or branch to Vercel
name: "Deploy"

on:
  release:
    types:
      - published
  push:
    branches:
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: "Deploy front-end"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"

      # Determine if the current ref is a release tag.
      - uses: ./.github/actions/ref_is_release
        id: is_release

      - name: "Deploy to Vercel"
        run: |
          prodRelease=""
          if [[ ${IS_RELEASE} == "true" ]]; then
            prodRelease="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRelease
        env:
          IS_RELEASE: ${{ steps.is_release.output.is_release }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_CLI_TOKEN }}
